// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvcua5BnBlA0SpUPw6dkfQo6vTy_7mAbk',
    appId: '1:417355569017:web:cdc8d66de0beb0dfdb41a8',
    messagingSenderId: '417355569017',
    projectId: 'prueba-13a33',
    authDomain: 'prueba-13a33.firebaseapp.com',
    storageBucket: 'prueba-13a33.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD5bWLXGsz8usdfHieE3M7Gu_o3jzaBls',
    appId: '1:417355569017:android:c26fe20bb8cc1300db41a8',
    messagingSenderId: '417355569017',
    projectId: 'prueba-13a33',
    storageBucket: 'prueba-13a33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjcqJS8HB_nHjMahdTkcLyQ45rE1MlZcQ',
    appId: '1:417355569017:ios:1666bdb660d7cc44db41a8',
    messagingSenderId: '417355569017',
    projectId: 'prueba-13a33',
    storageBucket: 'prueba-13a33.appspot.com',
    iosBundleId: 'com.example.authFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjcqJS8HB_nHjMahdTkcLyQ45rE1MlZcQ',
    appId: '1:417355569017:ios:1666bdb660d7cc44db41a8',
    messagingSenderId: '417355569017',
    projectId: 'prueba-13a33',
    storageBucket: 'prueba-13a33.appspot.com',
    iosBundleId: 'com.example.authFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvcua5BnBlA0SpUPw6dkfQo6vTy_7mAbk',
    appId: '1:417355569017:web:1bc3a9d4b4ff4660db41a8',
    messagingSenderId: '417355569017',
    projectId: 'prueba-13a33',
    authDomain: 'prueba-13a33.firebaseapp.com',
    storageBucket: 'prueba-13a33.appspot.com',
  );
}
